name: flutter_reactive_logout_example
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.0
  rxdart: ^0.28.0
  meta: ^1.17.0
  flutter_secure_storage: ^10.0.0
  logging: ^1.3.0
  dio: ^5.9.0
  json_annotation: ^4.9.0
  go_router: ^14.0.0
  equatable: ^2.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.12.0
  build_runner: ^2.10.5

flutter:
  uses-material-design: true
